// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using layedata;

namespace layedata.Migrations
{
    [DbContext(typeof(context))]
    [Migration("20210208072328_dore")]
    partial class dore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("layedata.role", b =>
                {
                    b.Property<int>("roleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("rolename")
                        .HasColumnType("int");

                    b.HasKey("roleid");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("layedata.userbomb", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("roleid")
                        .HasColumnType("int");

                    b.Property<string>("useractivatecode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("useractiveaya")
                        .HasColumnType("bit");

                    b.Property<string>("useremail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("userpassword")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("userid");

                    b.HasIndex("roleid");

                    b.ToTable("userbombs");
                });

            modelBuilder.Entity("layedata.userbomb", b =>
                {
                    b.HasOne("layedata.role", "role")
                        .WithMany("userbombs")
                        .HasForeignKey("roleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("layedata.role", b =>
                {
                    b.Navigation("userbombs");
                });
#pragma warning restore 612, 618
        }
    }
}
