// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using layedata;

namespace layedata.Migrations
{
    [DbContext(typeof(context))]
    [Migration("20210215173721_stringdatetime")]
    partial class stringdatetime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("layedata.dore", b =>
                {
                    b.Property<int>("doreid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("doreakharinberoozresany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("dorebargozary")
                        .HasColumnType("bit");

                    b.Property<string>("dorehgaymat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doreimageurl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dorematn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doremodars")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dorename")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("doresath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("doretedaddaneshamooz")
                        .HasColumnType("int");

                    b.Property<int>("doretedadgalase")
                        .HasColumnType("int");

                    b.Property<string>("doretedadsaatbargozary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("doreid");

                    b.ToTable("dores");
                });

            modelBuilder.Entity("layedata.role", b =>
                {
                    b.Property<int>("roleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("rolename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roleid");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("layedata.userbomb", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("roleid")
                        .HasColumnType("int");

                    b.Property<string>("useractivatecode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("useractiveaya")
                        .HasColumnType("bit");

                    b.Property<string>("useremail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("userpassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userid");

                    b.HasIndex("roleid");

                    b.ToTable("userbombs");
                });

            modelBuilder.Entity("layedata.videodore", b =>
                {
                    b.Property<int>("videoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("doreid")
                        .HasColumnType("int");

                    b.Property<string>("urlvideo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("videoid");

                    b.HasIndex("doreid");

                    b.ToTable("videodores");
                });

            modelBuilder.Entity("layedata.userbomb", b =>
                {
                    b.HasOne("layedata.role", "role")
                        .WithMany("userbombs")
                        .HasForeignKey("roleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("layedata.videodore", b =>
                {
                    b.HasOne("layedata.dore", "dore")
                        .WithMany("videodores")
                        .HasForeignKey("doreid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dore");
                });

            modelBuilder.Entity("layedata.dore", b =>
                {
                    b.Navigation("videodores");
                });

            modelBuilder.Entity("layedata.role", b =>
                {
                    b.Navigation("userbombs");
                });
#pragma warning restore 612, 618
        }
    }
}
